# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 393)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(180, 72, 111, 31))
        self.title.setObjectName("title")
        self.btn_generat = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generat.setGeometry(QtCore.QRect(180, 230, 75, 23))
        self.btn_generat.setObjectName("btn_generat")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(170, 110, 111, 16))
        self.result.setObjectName("result")
        self.cb_aphavit = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_aphavit.setGeometry(QtCore.QRect(160, 150, 131, 17))
        self.cb_aphavit.setObjectName("cb_aphavit")
        self.cd_numbers = QtWidgets.QCheckBox(self.centralwidget)
        self.cd_numbers.setGeometry(QtCore.QRect(160, 180, 111, 17))
        self.cd_numbers.setObjectName("cd_numbers")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "генерація паролів"))
        self.btn_generat.setText(_translate("MainWindow", "генерація"))
        self.result.setText(_translate("MainWindow", "тут буде результат"))
        self.cb_aphavit.setText(_translate("MainWindow", "Додати букви"))
        self.cd_numbers.setText(_translate("MainWindow", "Додати цифри"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
